on:
  [ registry_package, workflow_dispatch ]
jobs:
  javadocs:
    runs-on: ubuntu-latest
    steps:

      - name: Create src folder
        run: |
          mkdir src
          cd src

      - name: Checkout AutoUpdater
        uses: actions/checkout@v4

      - name: Create docs folder
        run: |
          cd ..
          mkdir docs
          cd docs

      - name: Checkout AutoUpdater Javadocs
        uses: actions/checkout@v4
        with:
          repository: "abelkrijgtalles/autoupdater-javadocs"

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.9.0
        with:
          java-version: 17

      - name: Generate Javadocs
        run: |
          cd ../src
          mvn package
          mvn javadoc -d ../docs nl.abelkrijgtalles.autoupdater
          cd ..